name: Activity Graph

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # allows manual trigger
  workflow_dispatch:
  # run on every push on the main branch
  push:
    branches:
      - main

jobs:
  build:
    name: Generate activity graph
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: Ashutosh00710/github-readme-activity-graph@v3
        with:
          username: "M1shaaa"
          theme: "cobalt"
          area: true
          hide_border: true
          hide_title: true
          radius: 50
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
